const products = [
  {id:'air-1',name:'Aurora Air Lite 无线耳机',price:299,rating:4.7,category:'无线耳机',brand:'Aurora',stock:31,desc:'轻量真无线，适合通勤和日常电话。'},
  {id:'air-2',name:'Orbit Pro 降噪耳机',price:499,rating:4.8,category:'无线耳机',brand:'Orbit',stock:12,desc:'主动降噪与多设备连接，适合长时间办公。'},
  {id:'air-3',name:'Sonic Mini 真无线耳机',price:199,rating:4.5,category:'无线耳机',brand:'Sonic',stock:42,desc:'入门级真无线耳机，主打轻便和续航。'},
  {id:'air-4',name:'Echo Studio 头戴耳机',price:699,rating:4.9,category:'无线耳机',brand:'Echo',stock:6,desc:'头戴式空间音频耳机，适合沉浸式听音。'},
  {id:'air-5',name:'Breeze Buds 无线耳机',price:389,rating:4.3,category:'无线耳机',brand:'Breeze',stock:18,desc:'半入耳设计，适合轻度使用。'},
  {id:'air-6',name:'Vega Sport 无线耳机',price:459,rating:4.6,category:'无线耳机',brand:'Vega',stock:22,desc:'IPX5 防水，适用于跑步和训练。'},
  {id:'air-7',name:'Pulse Max 降噪耳机',price:579,rating:4.8,category:'无线耳机',brand:'Pulse',stock:9,desc:'长续航降噪耳机，适合出差。'},
  {id:'air-8',name:'Lumen Go 真无线耳机',price:269,rating:4.4,category:'无线耳机',brand:'Lumen',stock:28,desc:'小巧便携，支持快速充电。'},
  {id:'key-1',name:'Nova 机械键盘',price:459,rating:4.6,category:'键盘',brand:'Nova',stock:15,desc:'75% 配列机械键盘。'},
  {id:'key-2',name:'Atlas 静音键盘',price:329,rating:4.7,category:'键盘',brand:'Atlas',stock:20,desc:'低噪办公键盘。'}
];
const state={query:'',category:'',maxPrice:null,minRating:null,sort:'recommended',page:1,pageSize:4};
const list=document.querySelector('#products'),count=document.querySelector('#result-count'),pageStatus=document.querySelector('#page-status');
function visibleProducts(){let items=products.filter(p=>(!state.query||p.name.includes(state.query)||p.category.includes(state.query)||p.brand.includes(state.query))&&(!state.category||p.category===state.category)&&(!state.maxPrice||p.price<=state.maxPrice)&&(!state.minRating||p.rating>=state.minRating));return items.sort((a,b)=>state.sort==='rating'?b.rating-a.rating||a.price-b.price:state.sort==='price-asc'?a.price-b.price:b.rating-a.rating||a.price-b.price)}
function render(){const items=visibleProducts(),pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const slice=items.slice((state.page-1)*state.pageSize,state.page*state.pageSize);count.textContent=`找到 ${items.length} 件符合条件的商品`;pageStatus.textContent=`第 ${state.page} / ${pages} 页`;list.innerHTML=slice.map(p=>`<article class="product-card" data-id="${p.id}" data-price="${p.price}" data-rating="${p.rating}" data-category="${p.category}"><div class="emoji">${p.category==='键盘'?'⌨️':'🎧'}</div><div class="product-copy"><p class="tag">${p.brand} · ${p.category}</p><h2 data-field="name">${p.name}</h2><p>评分 <b>${p.rating}</b> / 5.0 · 库存 ${p.stock}</p><strong>¥${p.price}</strong><button class="detail-button" data-product-id="${p.id}">查看详情</button></div></article>`).join('')||'<p class="empty">没有商品符合当前条件。</p>';document.querySelector('#previous-page').disabled=state.page===1;document.querySelector('#next-page').disabled=state.page===pages;}
function updateFilters(){state.category=document.querySelector('#category-filter').value;state.maxPrice=Number(document.querySelector('#price-filter').value)||null;state.minRating=Number(document.querySelector('#rating-filter').value)||null;state.sort=document.querySelector('#sort-filter').value;state.page=1;render()}
document.querySelector('#search-button').addEventListener('click',()=>{state.query=document.querySelector('#search-input').value.trim();state.page=1;render()});
document.querySelector('#search-input').addEventListener('keydown',event=>{if(event.key==='Enter')document.querySelector('#search-button').click()});
['#category-filter','#price-filter','#rating-filter','#sort-filter'].forEach(selector=>document.querySelector(selector).addEventListener('change',updateFilters));
document.querySelector('#reset-button').addEventListener('click',()=>{state.query='';state.category='';state.maxPrice=null;state.minRating=null;state.sort='recommended';state.page=1;document.querySelector('#search-input').value='';document.querySelector('#category-filter').value='';document.querySelector('#price-filter').value='';document.querySelector('#rating-filter').value='';document.querySelector('#sort-filter').value='recommended';render()});
document.querySelector('#previous-page').addEventListener('click',()=>{state.page--;render()});document.querySelector('#next-page').addEventListener('click',()=>{state.page++;render()});
list.addEventListener('click',event=>{const id=event.target.dataset.productId;if(!id)return;const product=products.find(item=>item.id===id);document.querySelector('#detail-content').innerHTML=`<p class="tag">${product.brand} · ${product.category}</p><h2>${product.name}</h2><p>${product.desc}</p><dl><dt>价格</dt><dd>¥${product.price}</dd><dt>评分</dt><dd>${product.rating} / 5.0</dd><dt>库存</dt><dd>${product.stock}</dd></dl>`;document.querySelector('#product-dialog').showModal()});
document.querySelector('#close-dialog').addEventListener('click',()=>document.querySelector('#product-dialog').close());render();
